version: '3.8'

services:
  nextjs-visor-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
    stdin_open: true
    tty: true
