version: '3.8'

services:
  nextjs-visor-frontend:
    build:
      context: .
      dockerfile: Dockerfile-front-visor
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.production
    stdin_open: true
    tty: true
