# Establecer la imagen base de Node.js
FROM node:20.17.0-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de dependencias
COPY package*.json ./

# Instalar las dependencias con el flag --legacy-peer-deps
RUN npm install --legacy-peer-deps

# Copiar el resto de los archivos de la aplicación
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Exponer el puerto en el que correrá la aplicación
EXPOSE 3001

# Comando para iniciar la aplicación en modo producción
CMD ["npm", "run", "start"]
